name = "alisareactionbot"
main = "src/index.js"
compatibility_date = "2026-02-22"

[vars]
BOT_TOKEN = "12345678:PAST-YOUR-BOT-TOKEN-HERE"
BOT_USERNAME = "AlisaReactionBot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "0"
RESTRICTED_CHATS = "1234,5678"
